
#ifndef INCLUDED_ASSGINMENT_GLOBAL_VARIABLE

#define INCLUDED_ASSGINMENT_GLOBAL_VARIABLE


#pragma once


#include"Variable.h"

#endif // !INCLUDED_ASSGINMENT_GLOBAL_VARIABLE

#define _SHARE_VARIABLE_FROM_ASSGINMENT